name: PR_Label_decider

on:
  pull_request:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review, review_requested]
    branches: [ master, '*dev*' ]
  
jobs:
  labeller:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # PR labeler action to add label as per the branch.
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: scripts/pr_tag_validator/pr-labeler.yml 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
