# This is a basic workflow to help you get started with Actions

name: PR Title Validation

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master, '*dev*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Validate PR Title
        run: |
          node ./scripts/pr_title_validator/index.js --prTitle="${PULL_REQUEST_TITLE}"
        env:
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
      - name: View PR author
        run: echo "This PR is opened by ${{github.event.pull_request.user.login}}"
      - name: View PR Object
        run: echo "Pull request object ${{github.event.label.name}}"
      - name: check PR label
        run: echo "PR label ${{github.event.pull_request.labels.*.name[0]}}"
